### ISSUE TITLE
bit lost following blog post

### ISSUE THREAD

**Issue by jbodhorn** [JonTheNiceGuy/rpirouter#1]
libComposite is new to me, first time I've used it, I was following along with your blog post, minus the ansible aspect, I'm somewhere at/between adding the (usb/ethernet)interface(s). I had got usb0 to show upon both host and device, but no usb1. 

The pi being the device should be usb1 and my laptop being the host should be usb0(that is correct right, or is it reversed?) I should see usb0 when I ip addr on my laptop and usb1 when I ip addr on the pi, or is it supposed to be vice versa and I'm ass backward as usual!?

Regardless of the adapter labeling there are some things I do not understand at all. 

"For starters, you need to put some magic strings into extra files to make this work – notably, you need to create a directory called os_desc/interface.rndis and stick two files called compatibility_id and sub_compatibility_id in there, which have the strings RNDIS and 5162001 in them, you also need to put the string RNDIS into configs/c.2/strings/0x409/configuration".

Touch mkdir, and nano all deny permission

"pi@raspberrypi:~ $ sudo find  / -name "os_desc"
/sys/kernel/config/usb_gadget/libComposite/os_desc
/sys/kernel/config/usb_gadget/libComposite/functions/rndis.usb0/os_desc
pi@raspberrypi:~ $ sudo mkdir /sys/kernel/config/usb_gadget/libComposite/functions/rndis.usb0/os_desc/interface.rndis
mkdir: cannot create directory ‘/sys/kernel/config/usb_gadget/libComposite/functions/rndis.usb0/os_desc/interface.rndis’: File exists
pi@raspberrypi:~ $ sudo nano /sys/kernel/config/usb_gadget/libComposite/functions/rndis.usb0/os_desc/interface.rndis/compatibility_id
pi@raspberrypi:~ $ sudo touch /sys/kernel/config/usb_gadget/libComposite/functions/rndis.usb0/os_desc/interface.rndis/compatibility_id
touch: cannot touch '/sys/kernel/config/usb_gadget/libComposite/functions/rndis.usb0/os_desc/interface.rndis/compatibility_id': Permission denied"

I have usb0 and usb1 in interfaces.d, but only usb0 shows up, and for some reason it only shows up on dev/pi, usb0 now doesn't show up on host/laptop like it was a bit ago, dunno why, can't get a usb* to appear on my laptop now

Why assign 2 ip to each adapter, you say 192.0.2.2 for the static usb0 and 192.0.2.17 for static usb1, then also tell dnsmasq to assign a dhcp ip to both usb* adapters, citing a range in dnsmasq that contains each adapter's static ip within the dhcp range in dnsmasq.conf or is that just supposed to get dnsmasq to use the static ip from interfaces/usb0/1? atm dnsmasq fails due to usb1 not existing 

I kept getting usb0 on pi having 2 ip addresses, the static assigned 192.0.2.2/28 and also an address similar to a windows internet connection sharing ip, 169.*.*.*, but I'm running linux, this pi has yet to meet any non linux OS and I dont have a dhcp server like dnsmasq running on the laptop. Can only guess but maybe (gnome)NetworkManager(on host, my laptop running linux) was assigning the 169.*.*.* address, now I don't see it at all. When I was getting the 169.*.*.* as a second ip for usb0 on the pi it showed as down with no ip on my laptop. now I only have 192.0.2.2 on pi and no usb* on laptop at all

**Comment by JonTheNiceGuy** [comment]
Hi,

Firstly, my sincere apologies for not spotting this sooner! My email had generously hidden the email at the bottom of a pile of other things!

Right, on to your issues.

> libComposite is new to me, first time I've used it

libComposite was new to me too - I was just poking around other blogs when I found it. The blog post is a summary of everything I found out!

> I'm somewhere at/between adding the (usb/ethernet)interface(s). I had got usb0 to show upon both host and device, but no usb1. The pi being the device should be usb1 and my laptop being the host should be usb0(that is correct right, or is it reversed?)

> Touch mkdir, and nano all deny permission

> I have usb0 and usb1 in interfaces.d, but only usb0 shows up, and for some reason it only shows up on dev/pi, usb0 now doesn't show up on host/laptop like it was a bit ago, dunno why, can't get a usb* to appear on my laptop now

Regarding usb0 and usb1, these are on the pi (the "device" machine) and are the ECM/CDC and RNDIS "interfaces" (RNDIS for Windows, ECM/CDC for "everything else"). If you're not seeing both of these on the Pi, then you've had an issue somewhere in your creation of these interfaces. I know you're following along without using Ansible, but you might find this file helpful: [libComposite.sh](https://github.com/JonTheNiceGuy/rpirouter/blob/StateInterfaceUpOnly/roles/jontheniceguy.rpirouter/files/libComposite.sh)

If you're messing in the `/sys/kernel/config/usb_gadget` file tree by hand, you need to reset the UDC file (I do `echo "" > /sys/kernel/config/usb_gadget/libComposite/UDC; ls /sys/class/udc >/sys/kernel/config/usb_gadget/libComposite/UDC` - check your paths are the same!), otherwise it doesn't appear to re-advertise itself to the non-Pi (the "host" machine). It may also cut off the "device" from the "host", which might be why you aren't seeing it on the laptop.

Another thing to note about the `/sys/kernel/config/usb_gadget` tree is that if you've created a path, it creates other files in there too. You may end up not being able to edit those files after they're done, and you certainly often can't remove the files either. Again, I'd probably use a script to create the files in those paths, and if they don't work the way you're expecting, reboot and try again (the `/sys/kernel/config/usb_gadget` tree is not retained between boots).

> Why assign 2 ip to each adapter, you say 192.0.2.2 for the static usb0 and 192.0.2.17 for static usb1

So, you've got two interfaces, because we've got one for RNDIS and one for ECM/CDC. Unless we *also* create a bridge interface that we add these two interfaces to (which was thoroughly outside the remit of this post), we can't assign the same IP address to both interfaces, so we allocate two separate IP addresses. A later blog post may well cover having that use case. The Ansible role does already cover creating a bridge interface.

> then also tell dnsmasq to assign a dhcp ip to both usb* adapters, citing a range in dnsmasq that contains each adapter's static ip within the dhcp range in dnsmasq.conf or is that just supposed to get dnsmasq to use the static ip from interfaces/usb0/1?

We use DNSMasq to assign an IP address for the "host", not the "device". It's using the IP address of the interface as a "seed" to prompt DNSMasq to use that as it's address range.

>  atm dnsmasq fails due to usb1 not existing

Yes, it'll do that 😉 Just comment out all the usb1 stuff for now, or fix the missing usb1 interface with the script I pointed to before.

> I kept getting usb0 on pi having 2 ip addresses, the static assigned 192.0.2.2/28 and also an address similar to a windows internet connection sharing ip, 169..., but I'm running linux, this pi has yet to meet any non linux OS and I dont have a dhcp server like dnsmasq running on the laptop.

169.254.0.0/16 is the address range for the "Link Local Addresses" ([RFC3927](https://datatracker.ietf.org/doc/html/rfc3927)) and is used to generate a dynamic, yet repeatable, address whenever a DHCP server fails to assign an IP address. You'll probably find that one of the config files for the usb0 interface on the pi is telling it to pick up a DHCP address, but it can't find one... or it might be something else that's gone wrong!

Either way, good luck! I hope some of this helps you! Please let me know!

**Comment by jbodhorn** [comment]
Thank you much for your reply, I had given up trying to get it working, it's just been sitting since. I can't wait to play some more now, hopefully I get it working
